# Generated by Django 3.1 on 2020-08-21 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='thickness_diameter',
            field=models.PositiveIntegerField(default=1, verbose_name='ЗНАЧЕНИЕ ТОЛЩИНЫ ИЛИ ДИАМЕТРА ПРОКАТА'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='assortment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.assortment', verbose_name='ПРОКАТ'),
        ),
    ]
