# Generated by Django 3.1 on 2020-08-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20200821_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('file', models.ImageField(upload_to='SYSTEM_FILES')),
            ],
        ),
    ]
