# Generated by Django 3.1 on 2020-08-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20200818_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.FileField(null=True, upload_to='TABLES', verbose_name='ТАБЛИЦА'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='title',
            field=models.CharField(default='DEFAULT', max_length=50, verbose_name='НАЗВАНЕ ОПЕРАЦИИ'),
        ),
    ]
