# Generated by Django 3.1 on 2020-08-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20200818_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='position',
            name='qr_code',
            field=models.ImageField(default='QR_CODE/default.png', upload_to='QR_CODE', verbose_name='КОД ДЕТАЛИ'),
        ),
    ]
