# Generated by Django 3.1 on 2020-09-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
