# Generated by Django 3.1 on 2020-08-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20200818_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='code',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
