# Generated by Django 3.1 on 2020-08-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20200818_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code_list',
            field=models.FileField(null=True, upload_to='QR_CODE_LIST', verbose_name='ФАЙЛ С КОДАМИ'),
        ),
    ]
