# Generated by Django 3.1 on 2020-09-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('C', 'Constructor'), ('E', 'Electronic'), ('P', 'Production'), ('M', 'Managment'), ('A', 'Ather')], default='A', max_length=20, verbose_name='ProfileStatus'),
        ),
    ]
