# Generated by Django 3.1 on 2020-08-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_order_qr_code_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='draw_archive',
            field=models.FileField(null=True, upload_to='DRAW_ARCHIVE', verbose_name='АРХИВ С PDF ЧЕРТЕЖАМИ'),
        ),
    ]
