# Generated by Django 3.1 on 2020-09-16 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fields_Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_alianse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alianse', to='MainApp.operation', verbose_name='ALIENSE')),
                ('operation_cncmw', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cncmw', to='MainApp.operation', verbose_name='CNCMetallWorks')),
                ('operation_dr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dr', to='MainApp.operation', verbose_name='Drugoe')),
                ('operation_niilr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='niilr', to='MainApp.operation', verbose_name='NIILR')),
                ('operation_oz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oz', to='MainApp.operation', verbose_name='OZ')),
                ('operation_pk1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk1', to='MainApp.operation', verbose_name='PokritieKh')),
                ('operation_pk2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk2', to='MainApp.operation', verbose_name='PokritieKy')),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MainApp.position')),
            ],
        ),
    ]
